name: FLutter_Tests

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from PR/Commit
        uses: actions/checkout@v2
        
      - name: View files
        run: |
          cat app/pubspec.yaml
      
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2.0.1
        with:
          flutter-version: '2.0.1'
      
      - name: Restore packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze
        
      - name: Run tests
        run: flutter test --coverage
